### ISSUE TITLE
Back button not working in android

### ISSUE THREAD

**Issue by Piyuhs** [Divyansh200600/PulseZest-Console#3]
when we click on the  view button to see the image then we are unable to back in the phone.

**Suggestion**
when click on view  button then  the image show in  the popup and also  add the cross button in popup...

**Comment by im-divxnshh** [comment]
![image](https://github.com/PulseZest-Inovation/PulseZest-Console/assets/129685502/9a099881-714d-439c-8181-f44a24c80218)


done

**Comment by PulseZest** [comment]
Grate Work 👏🏻
